"""
Generate the cinematic_warm.cube 3D LUT for video color grading.

This generates a 17-point 3D LUT with a cinematic warm/teal look:
- Contrast S-curve (lift shadows, roll off highlights)
- Warm color temperature (red shift, blue cut)
- Subtle teal/orange grade for skin tones

Usage: python generate_lut.py
"""

import math


def s_curve(v: float, strength: float = 0.15) -> float:
    """Apply an S-curve contrast adjustment."""
    # Center around 0.5, pull midtones
    if v < 0.5:
        return v - strength * (0.5 - v) * (1 - v / 0.5)
    else:
        return v + strength * (v - 0.5) * (v / 0.5)


def generate_17pt_lut() -> list[tuple[float, float, float]]:
    """Generate a 17^3 3D LUT with cinematic warm grade."""
    entries = []
    size = 17
    for b in range(size):
        for g in range(size):
            for r in range(size):
                # Normalize to [0, 1]
                ri = r / (size - 1)
                gi = g / (size - 1)
                bi = b / (size - 1)

                # Apply S-curve contrast to all channels
                ro = s_curve(ri, 0.12)
                go = s_curve(gi, 0.10)
                bo = s_curve(bi, 0.10)

                # Warm grade: boost red, cut blue
                ro = min(1.0, ro * 1.04)
                bo = max(0.0, bo * 0.92)

                # Teal/orange: shift midtones green toward teal
                # More aggressive on shadows, less on highlights
                teal = 0.03 * (1.0 - go)
                go = min(1.0, go + teal)
                bo = min(1.0, bo + teal * 0.7)

                # Subtle shadow saturation bump
                shadow_w = max(0.0, 1.0 - ri * 3)
                ro = min(1.0, ro + shadow_w * 0.02)

                # Clamp
                ro = max(0.0, min(1.0, ro))
                go = max(0.0, min(1.0, go))
                bo = max(0.0, min(1.0, bo))

                entries.append((ro, go, bo))
    return entries


def write_cube(path: str, entries: list[tuple[float, float, float]]):
    """Write 3D LUT in .cube format."""
    size = round(len(entries) ** (1 / 3))
    assert size ** 3 == len(entries), f"{len(entries)} is not a perfect cube"

    lines = [
        'TITLE "AIComics Cinematic Warm"',
        "",
        "# 17-point 3D LUT",
        "# Generated by AIComics video quality upgrade pipeline",
        "# Applies: S-curve contrast + warm color cast + teal/orange grade",
        "",
        f"LUT_3D_SIZE {size}",
        "",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
    ]

    for r, g, b in entries:
        lines.append(f"{r:.6f} {g:.6f} {b:.6f}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"✓ Wrote {size}^3 LUT ({len(entries)} entries) to {path}")


if __name__ == "__main__":
    import os
    out_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(out_dir, "cinematic_warm.cube")
    entries = generate_17pt_lut()
    write_cube(out_path, entries)
