// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"创作台","path":"/creator","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"项目","path":"/projects","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"总览","path":"/dashboard","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"剧集","path":"/episodes","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"任务","path":"/jobs","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"批次","path":"/batches","parentId":"ant-design-pro-layout","id":"8"},"9":{"name":"服务商","path":"/provider","parentId":"ant-design-pro-layout","id":"9"},"10":{"name":"复盘","path":"/review","parentId":"ant-design-pro-layout","id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__CreatorWorkspace__index" */'@/pages/CreatorWorkspace/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Projects__index" */'@/pages/Projects/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Episodes__index" */'@/pages/Episodes/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Jobs__index" */'@/pages/Jobs/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Batches__index" */'@/pages/Batches/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Provider__index" */'@/pages/Provider/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Review__index" */'@/pages/Review/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/eric/Desktop/herness/AIComics/10_System/web/frontend/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
